# Parameters for keyboard_mapper/keyboard_mapper
# speed_gain: 0.4293,0.60
speed_gain: 10
# steer_gain: 8.586,5.45
steer_gain: 60
bicycle_kinematics: 0.0
steer_angle_gain: 1.04
simulated_vehicle_length: 0.18
